### ISSUE TITLE
 cannot load such file

### ISSUE THREAD

**Issue by googya** [d-unseductable/rust_sidekiq#1]
``` shell
bundle exec ruby bin/server.rb
```

got: 

``` shell
bin/server.rb:1:in `require_relative': cannot load such file -- /private/tmp/rust_sidekiq/ext/rust_sidekiq/target/release/librust_sidekiq (LoadError)
    from bin/server.rb:1:in `<main>'
```

``` shell
 tree target/release
target/release
├── build
│   └── ruby-sys-11ae9626f774f978
│       ├── build-script-build
│       ├── build_script_build.dSYM
│       │   └── Contents
│       │       ├── Info.plist
│       │       └── Resources
│       │           └── DWARF
│       │               └── build_script_build
│       ├── out
│       └── output
├── deps
│   ├── libbyteorder-3c611b87c8dea62c.rlib
│   ├── liblibc-244e498787c54b2a.rlib
│   ├── libmatches-9fe41d795c48d446.rlib
│   ├── librand-a5887f89c2d0b20b.rlib
│   ├── libredis-9ad845bff6cf218e.rlib
│   ├── libruby_sys-3eba6fe4a000ece4.rlib
│   ├── libruru-fc306bd988464085.rlib
│   ├── librustc_serialize-378abee831ab0f27.rlib
│   ├── libsha1-321a911281ab9807.rlib
│   ├── libunicode_bidi-bf04a064e2f70472.rlib
│   ├── libunicode_normalization-71cf52fb879ac8e6.rlib
│   ├── liburl-5f84c10c7599936e.rlib
│   └── libuuid-dfccd4cce1524d42.rlib
├── examples
├── librust_sidekiq.dylib
└── native
```

**Comment by d-unsed** [comment]
Hey @googya!

Thanks for reporting this issue!

Please try to copy the compiled `.dylib` file to `.bundle`

``` bash
$ cp ext/rust_sidekiq/target/release/librust_sidekiq.dylib ext/rust_sidekiq/target/release/librust_sidekiq.bundle
```

and restart the server

**Comment by googya** [comment]
@d-unseductable Great, it works!
